# Generated by Django 3.0.6 on 2020-05-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=20)),
                ('tel', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(max_length=50)),
                ('x', models.CharField(max_length=50)),
                ('y', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=250)),
                ('public', models.TextField(blank=True, null=True)),
                ('parking', models.TextField(blank=True, null=True)),
                ('type', models.CharField(default='기타', max_length=50)),
                ('img', models.URLField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
